//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing.Drawing2D;
using System;

namespace AsoftTest.Models
{
    public class Test
    {
       
            public string UserID { get; set; }
            public string UserName { get; set; }
            public string Password { get; set; }
            public string Email { get; set; }
            public string Tel { get; set; }
            public byte Disable { get; set; }

    }
}